import esbuild from 'esbuild';
import esbuildSvelte from 'esbuild-svelte';
import sveltePreprocess from 'svelte-preprocess';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	plugins: [
		esbuildSvelte({
			// verbatimModuleSyntax stops the TS-stripping step from eliding an
			// import that's only referenced via Svelte's `$store` auto-subscription
			// sugar (e.g. `$dashboardData`) - TS's default elision doesn't
			// recognize that as a "use" of the plain `dashboardData` import, so it
			// silently drops the import and the store reference throws
			// ReferenceError at runtime. Bit us once already (see git log).
			preprocess: sveltePreprocess({
				typescript: { compilerOptions: { verbatimModuleSyntax: true } },
			}),
			compilerOptions: { css: 'injected' },
		}),
	],
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
